name: E2E Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  e2e:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: testdb
        ports: [5432:5432]
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      PG_HOST: localhost
      PG_PORT: 5432
      PG_USER: postgres
      PG_PASSWORD: postgres
      PG_DATABASE: testdb
      REACT_APP_API_BASE: http://localhost:5000

    steps:
    - uses: actions/checkout@v3
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install backend dependencies
      run: |
        cd server
        npm ci

    - name: Start backend
      run: |
        cd server
        nohup node index.js > backend.log 2>&1 &

    - name: Install frontend dependencies
      run: |
        cd client
        npm ci

    - name: Build frontend
      run: |
        cd client
        npm run build

    - name: Serve frontend
      run: |
        cd client
        npx serve -s build -l 3000 > frontend.log 2>&1 &
        
    - name: Install Playwright and its dependencies
      run: |
        cd client
        npx playwright install --with-deps

    - name: Run Playwright tests
      run: |
        cd client
        npx playwright test



